// Optional live-site check; requires Internet. No AI calls or account credentials.
import { chromium } from 'playwright';import { createServer } from '../scripts/serve.mjs';import { readFile,writeFile,mkdir } from 'node:fs/promises';import assert from 'node:assert/strict';
const server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`,url='https://www.cao.go.jp/others/csi/security/20250812notice.html';
const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1600,height:1100}});await mkdir('verification/windows',{recursive:true});
await page.addInitScript(()=>{const attach=Element.prototype.attachShadow;Element.prototype.attachShadow=function(o){const s=attach.call(this,o);if(this.hasAttribute('data-yomi-root'))window.__testShadow=s;if(this.hasAttribute('data-yomi-annotation-layer'))window.__annotationShadow=s;return s;};});
await page.route('**/dictionary/*.json',async route=>{const response=await page.request.get(base+new URL(route.request().url()).pathname);await route.fulfill({response});});
const rects=()=>page.evaluate(()=>Object.fromEntries(['h1','body','button[aria-controls="globalNavDrop-01"]'].map(s=>[s,document.querySelector(s)?.getBoundingClientRect().toJSON()])));
try{
 await page.goto(url,{waitUntil:'networkidle'});await page.screenshot({path:'verification/windows/cabinet-before.png'});const before=await rects();
 const observed=await page.evaluate(()=>[...document.querySelectorAll('h1,button[aria-controls="globalNavDrop-01"]')].map(e=>({tag:e.tagName,text:e.textContent,font:getComputedStyle(e).fontSize,lineHeight:getComputedStyle(e).lineHeight,html:e.outerHTML})));
 await page.addScriptTag({content:await readFile('demo/bridge.js','utf8')});await page.addScriptTag({content:await readFile('demo/yomi-reader.js','utf8')});await page.waitForFunction(()=>document.querySelector('h1 rt'),null,{timeout:60000});await page.waitForFunction(()=>[...document.querySelectorAll('[data-yomi-annotation-anchor]')].some(e=>e.textContent==='せいさく'));await page.waitForTimeout(300);const after=await rects();assert.deepEqual(after,before);
 const q=await page.locator('button[aria-controls="globalNavDrop-01"]').evaluate(e=>{const r=document.createRange();const w=document.createTreeWalker(e,NodeFilter.SHOW_TEXT,{acceptNode:n=>n.parentElement.closest('[data-yomi-ui]')?NodeFilter.FILTER_REJECT:NodeFilter.FILTER_ACCEPT});const node=w.nextNode();r.setStart(node,0);r.setEnd(node,1);const b=r.getBoundingClientRect();return {x:b.x+b.width/2,y:b.y+b.height/2};});await page.mouse.move(q.x,q.y);await page.waitForFunction(()=>window.__testShadow.querySelector('.word').textContent==='内閣府');await page.waitForTimeout(260);await page.screenshot({path:'verification/windows/cabinet-after.png'});
 await page.keyboard.press('Escape');await page.waitForTimeout(220);await page.locator('button[aria-controls="globalNavDrop-01"]').click();assert.equal(await page.locator('button[aria-controls="globalNavDrop-01"]').getAttribute('aria-expanded'),'true');
 const result={date:new Date().toISOString(),url,browser:await browser.version(),observed,before,after,results:['Native top navigation displays kana and opens 内閣府 card','Single-line H1 annotations restored','H1, body and nav bounding boxes unchanged','Original navigation button still expands menu'],ai:'Disabled'};await writeFile('verification/windows/cabinet-results.json',JSON.stringify(result,null,2));console.log('PASS',result.results);
}finally{await browser.close();await new Promise(r=>server.close(r));}
