import {chromium} from 'playwright';import {createServer} from '../scripts/serve.mjs';import {mkdir,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1400,height:1000}}),results=[],errors=[],dir='verification/categories';await mkdir(dir,{recursive:true});page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{const attach=Element.prototype.attachShadow;Element.prototype.attachShadow=function(o){const s=attach.call(this,o);if(this.hasAttribute('data-yomi-root'))window.ui=s;return s;};});
const click=s=>page.evaluate(s=>{const e=ui.querySelector(s);if(!e)throw Error(s);e.click();},s),fill=(s,value)=>page.evaluate(({s,value})=>{ui.querySelector(s).value=value;},{s,value}),text=s=>page.evaluate(s=>ui.querySelector(s).textContent,s);
const waitPicker=()=>page.waitForFunction(()=>!ui.querySelector('.collection-picker').hidden);
const saved=()=>page.waitForFunction(()=>ui.querySelector('.collection-picker').hidden);
const pass=s=>{results.push(s);console.log('PASS',s);};
async function create(name){await fill('.collection-name',name);await click('.collection-create');await page.waitForFunction(name=>[...ui.querySelectorAll('.category-choice span')].some(e=>e.textContent===name),name);}
async function hover(){await page.locator('#english').scrollIntoViewIfNeeded();const p=await page.locator('#english').evaluate(el=>{const w=document.createTreeWalker(el,NodeFilter.SHOW_TEXT,{acceptNode:n=>n.parentElement.closest('[data-yomi-ui],rt')?NodeFilter.FILTER_REJECT:NodeFilter.FILTER_ACCEPT});while(w.nextNode()){const at=w.currentNode.nodeValue.indexOf('learned');if(at<0)continue;const r=document.createRange();r.setStart(w.currentNode,at);r.setEnd(w.currentNode,at+1);const b=r.getBoundingClientRect();return {x:b.x+b.width/2,y:b.y+b.height/2};}});await page.mouse.move(p.x,p.y);await page.waitForFunction(()=>ui.querySelector('.word').textContent==='learned');}
async function collect(){await page.evaluate(()=>[...ui.querySelectorAll('.tooltip .actions button')].find(e=>e.textContent.includes('收录')).click());await waitPicker();}
async function category(name){await page.evaluate(name=>[...ui.querySelectorAll('.category-link')].find(e=>e.querySelector('span').textContent===name).click(),name);}
async function shot(name){await page.waitForTimeout(230);await page.screenshot({path:dir+'/'+name+'.png'});}
try{
 await page.goto(base+'/precision.html');await hover();await collect();await create('英语');await create('新闻');assert.equal(await page.evaluate(()=>ui.querySelectorAll('.collection-choices input:checked').length),2);await shot('collect-multiple');await click('.collection-save');await saved();await page.waitForFunction(()=>ui.querySelector('.learning-status').textContent.includes('已收录'));await collect();assert.equal(await page.evaluate(()=>ui.querySelectorAll('.collection-choices input:checked').length),2);await page.keyboard.press('Escape');await saved();pass('Collect picker creates categories, selects multiple memberships and reopens with saved choices; Esc cancels without changing them');
 await click('.library-launch');await page.waitForFunction(()=>ui.querySelector('.library-count').textContent.includes('1 条'));await category('英语');assert.match(await text('.library-count'),/1 条/);await category('新闻');assert.match(await text('.library-count'),/1 条/);await shot('library-sidebar');
 await page.reload();await click('.library-launch');await page.waitForFunction(()=>ui.querySelectorAll('.category-link').length===4);await category('全部资料');assert.match(await text('.library-count'),/1 条/);pass('Two categories share a single learning item; refresh preserves catalog and memberships');
 await click('.library-edit');await page.waitForFunction(()=>ui.querySelector('.detail-categories')?.textContent.includes('新闻'));await page.evaluate(()=>[...ui.querySelectorAll('.library-detail button')].find(e=>e.textContent.includes('选择分类')).click());await waitPicker();await page.evaluate(()=>[...ui.querySelectorAll('.category-choice')].find(e=>e.textContent==='新闻').querySelector('input').checked=false);await click('.collection-save');await saved();await page.waitForFunction(()=>ui.querySelector('.detail-categories').textContent==='英语');await click('.library-detail > .action');await category('新闻');assert.match(await text('.library-count'),/0 条/);pass('Library item details can change membership without copying the item or changing its learning record');
 await click('.manage-categories');await page.evaluate(()=>{const row=[...ui.querySelectorAll('.category-manage-row')].find(e=>e.querySelector('input').value==='英语');row.querySelector('input').value='English / 工作';row.querySelector('button').click();});await page.waitForFunction(()=>[...ui.querySelectorAll('.category-link span')].some(e=>e.textContent==='English / 工作'));await category('English / 工作');assert.match(await text('.library-count'),/1 条/);await shot('category-manager');
 await page.evaluate(()=>{const row=[...ui.querySelectorAll('.category-manage-row')].find(e=>e.querySelector('input').value==='English / 工作');row.querySelectorAll('button')[1].click();});await page.waitForFunction(()=>![...ui.querySelectorAll('.category-link span')].some(e=>e.textContent==='English / 工作'));await category('未分类');assert.match(await text('.library-count'),/1 条/);pass('Rename keeps membership; deleting a category preserves its word and exposes it in Unfiled when no live categories remain');
 await click('.custom-add');await fill('[data-edit=word]','안녕하세요');await fill('[data-edit=meaning]','您好');await page.evaluate(()=>[...ui.querySelectorAll('.library-detail button')].find(e=>e.textContent==='收录自定义项目').click());await waitPicker();await create('韩语');await click('.collection-save');await saved();await page.waitForFunction(()=>ui.querySelector('.library-detail h2')?.textContent==='안녕하세요');await click('.library-detail > .action');await category('韩语');assert.match(await text('.library-results'),/안녕하세요/);await shot('custom-language');pass('Custom entries in another language can be created and filed into a user-defined language category');
 await click('.library-edit');await page.waitForFunction(()=>ui.querySelector('.detail-categories'));await page.evaluate(()=>[...ui.querySelectorAll('.library-detail button')].find(e=>e.textContent.includes('选择分类')).click());await waitPicker();await fill('.collection-name','韩语');await click('.collection-create');await page.waitForFunction(()=>ui.querySelector('.collection-error').textContent.includes('同名'));assert.equal(await page.evaluate(()=>ui.querySelectorAll('.collection-choices input').length),2);await click('.collection-cancel');await saved();
 await click('.library-detail > .action');await page.setViewportSize({width:390,height:820});await page.emulateMedia({colorScheme:'dark',reducedMotion:'reduce'});await page.waitForTimeout(250);assert.ok(await page.evaluate(()=>{const e=ui.querySelector('.library'),b=e.getBoundingClientRect();return b.left>=-1&&b.right<=innerWidth+1&&e.scrollWidth<=e.clientWidth+1;}));await shot('narrow-dark');pass('Duplicate names show a local error; Library adapts to a narrow dark viewport without horizontal overflow');
 assert.deepEqual(errors,[]);await writeFile(dir+'/results.json',JSON.stringify({date:new Date().toISOString(),browser:await browser.version(),results,errors},null,2));
}catch(e){await shot('failure');throw e;}finally{await browser.close();await new Promise(r=>server.close(r));}
