import { chromium } from 'playwright';
import { createServer } from '../scripts/serve.mjs';
import { mkdir,readFile,writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],results=[];
const dir='verification/interactions';await mkdir(dir,{recursive:true});page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{const attach=Element.prototype.attachShadow;Element.prototype.attachShadow=function(options){const s=attach.call(this,options);if(this.hasAttribute('data-yomi-root'))window.__testShadow=s;return s;};});
const bundle=await readFile('demo/yomi-reader.js','utf8');await page.route('**/yomi-reader.js',r=>r.fulfill({contentType:'text/javascript',body:`window.before=Object.fromEntries(['heading','nav','grammar','compact'].map(id=>[id,JSON.stringify(document.getElementById(id).getBoundingClientRect().toJSON())]));\n${bundle}`}));
const ui=async(s,fn='click',value)=>{if(fn==='click'){await page.evaluate(s=>window.__testShadow.querySelector(s).scrollIntoView({block:'nearest'}),s);await page.waitForTimeout(80);const b=await ui(s,'rect');return page.mouse.click(b.x+b.width/2,b.y+b.height/2);}return page.evaluate(({s,fn,value})=>{const e=window.__testShadow.querySelector(s);if(fn==='text')return e.textContent;if(fn==='rect')return e.getBoundingClientRect().toJSON();if(fn==='value')e.value=value;else if(fn==='checked')e.checked=value;},{s,fn,value});};
const pass=s=>{results.push(s);console.log('PASS',s);};
async function point(selector,word,shadow=false){return page.evaluate(({selector,word,shadow})=>{const e=(shadow?window.__testShadow:document).querySelector(selector),w=document.createTreeWalker(e,NodeFilter.SHOW_TEXT,{acceptNode:n=>n.parentElement.closest('rt')?NodeFilter.FILTER_REJECT:NodeFilter.FILTER_ACCEPT});let text='';const pieces=[];while(w.nextNode()){pieces.push({n:w.currentNode,start:text.length});text+=w.currentNode.nodeValue;}const at=text.indexOf(word);if(at<0)throw Error(word);const piece=pieces.findLast(p=>p.start<=at),r=document.createRange();r.setStart(piece.n,at-piece.start);r.setEnd(piece.n,at-piece.start+1);const b=r.getBoundingClientRect();return {x:b.x+b.width/2,y:b.y+b.height/2};},{selector,word,shadow});}
async function hover(selector,word,shadow=false,expected=word){await page.evaluate(({selector,shadow})=>(shadow?window.__testShadow:document).querySelector(selector).scrollIntoView({block:'nearest'}),{selector,shadow});await page.waitForTimeout(240);const p=await point(selector,word,shadow);await page.mouse.move(p.x,p.y);try{await page.waitForFunction(({expected,shadow})=>{const s=window.__testShadow;return s.querySelector(shadow?'.child-word':'.word').textContent===expected;},{expected,shadow});}catch(error){await screenshot('failure');console.log({selector,word,p,state:await ui('.child-word','text'),parent:await ui('.word','text')});throw error;}}
const waitState=s=>page.waitForFunction(s=>window.__testShadow.querySelector('.example-panel').dataset.state===s,s);
async function screenshot(name){await page.waitForTimeout(260);await page.screenshot({path:`${dir}/${name}.png`});}
async function inside(){assert.ok(await page.evaluate(()=>[...window.__testShadow.querySelectorAll('.tooltip,.example-panel')].filter(e=>!e.hidden).every(e=>{const b=e.getBoundingClientRect(),v=visualViewport;return b.left>=v.offsetLeft-1&&b.top>=v.offsetTop-1&&b.right<=v.offsetLeft+v.width+1&&b.bottom<=v.offsetTop+v.height+1;})));}
async function drag(selector,dx,dy){await page.waitForTimeout(260);const before=await ui(selector,'rect'),bar=await ui(selector+' .bar','rect');await page.mouse.move(bar.x+70,bar.y+15);await page.mouse.down();await page.mouse.move(bar.x+70+dx,bar.y+15+dy,{steps:10});await page.mouse.up();await page.waitForTimeout(30);const after=await ui(selector,'rect');assert.ok(Math.abs(after.x-before.x)>20||Math.abs(after.y-before.y)>20);await inside();return after;}
await page.route('**/mock/chat/completions',async route=>{const word=JSON.parse(route.request().postDataJSON().messages[1].content).word;if(word==='slowword')await new Promise(r=>setTimeout(r,900));if(word==='networkfailure')return route.abort('failed');try{await route.fulfill({json:{choices:[{message:{content:JSON.stringify({meaning:word+' 的测试释义',example:'slowword fastword networkfailure learn 日本語。',usage:'模拟响应，用于验证子查询。'})}}]}});}catch{}});
try{
 await page.goto(base+'/interactions.html');await page.waitForFunction(()=>document.querySelector('#heading rt'),null,{timeout:60000});await page.waitForTimeout(300);
 for(const id of ['heading','nav','grammar','compact'])assert.equal(await page.locator('#'+id).evaluate(e=>JSON.stringify(e.getBoundingClientRect().toJSON())),await page.evaluate(id=>window.before[id],id));assert.equal(await page.locator('#nav [data-yomi-token],#compact rt').count(),0);
 await hover('#nav','内閣府');await page.keyboard.press('Escape');await page.waitForTimeout(230);await page.locator('#nav').click();assert.equal(await page.locator('#clicks').textContent(),'1');assert.equal(await page.locator('#nav').getAttribute('aria-expanded'),'true');pass('Tight native navigation buttons are queryable without modifying DOM or breaking their click; spacious heading annotations preserve all tested boxes');
 await hover('#heading','内閣府');await screenshot('heading-query');await page.keyboard.press('Escape');await page.waitForTimeout(230);
 await hover('#grammar','ものの');await ui('.tooltip .details summary');const dragged=await drag('.tooltip',-220,70);assert.match(await ui('.word','text'),/ものの/);
 await hover('.tooltip .example','ものの',true);await waitState('success');assert.match(await ui('.child-meta','text'),/GRAMMAR/);
 await hover('.tooltip .example','個人消費',true);await waitState('success');assert.equal(await ui('.word','text'),'ものの');assert.equal(await ui('.child-word','text'),'個人消費');assert.ok(await page.evaluate(()=>window.__testShadow.querySelector('.tooltip .example-active')?.textContent==='個人消費'));await screenshot('japanese-child');await drag('.example-panel',40,90);pass('Main and child cards drag within viewport; Japanese example grammar and compounds open separately with parent and active term preserved');
 await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>window.__testShadow.querySelector('.example-panel').hidden),true);assert.equal(await page.evaluate(()=>window.__testShadow.querySelector('.tooltip').hidden),false);assert.equal((await ui('.tooltip','rect')).x,dragged.x);await page.keyboard.press('Escape');await page.waitForTimeout(230);
 await hover('#english','learn');await ui('.tooltip .details summary');await hover('.tooltip .example','learn',true);await waitState('success');await ui('.child-details summary');await hover('.child-example','new',true);assert.equal(await ui('.child-word','text'),'new');await ui('.child-back');assert.equal(await ui('.child-word','text'),'learn');assert.equal(await ui('.word','text'),'learn');await ui('.child-collect');await page.waitForFunction(()=>!window.__testShadow.querySelector('.collection-picker').hidden);await ui('.collection-save');await page.waitForFunction(()=>window.__testShadow.querySelector('.child-collect').textContent.includes('已收录'));pass('English examples support nested lookup, bounded back history and one-click collection; Esc closes only the child');
 await ui('.child-details summary');await hover('.child-example','something',true);await ui('.child-ai');await page.waitForFunction(()=>window.__testShadow.querySelector('.child-error').textContent.includes('尚未配置'));await screenshot('unconfigured-ai');
 await ui('.launcher');await ui('[data-tab=ai]');await ui('[name=aiEnabled]','checked',true);await ui('[name=endpoint]','value',base+'/mock/chat/completions');await ui('[name=model]','value','test');await ui('.save');await ui('.settings .close');await hover('#english','quizzaciously');await page.waitForFunction(()=>window.__testShadow.querySelector('.tooltip').dataset.state==='success');await ui('.tooltip .details summary');
 await hover('.tooltip .example','slowword',true);await waitState('loading');await hover('.tooltip .example','fastword',true);await waitState('success');await page.waitForTimeout(1000);assert.equal(await ui('.child-word','text'),'fastword');assert.equal(await ui('.word','text'),'quizzaciously');await hover('.tooltip .example','networkfailure',true);await waitState('error');await hover('.tooltip .example','learn',true);await waitState('success');pass('Child requests ignore canceled slow responses; missing AI and network failures remain local and basic lookup still works');
 await hover('.tooltip .example','日本語',true);await waitState('success');assert.match(await ui('.child-meta','text'),/JA/);await page.keyboard.press('Escape');
 const selected=await page.evaluate(()=>{const r=document.createRange();r.selectNodeContents(window.__testShadow.querySelector('.tooltip .example'));getSelection().removeAllRanges();getSelection().addRange(r);return getSelection().toString();});assert.equal(selected,'slowword fastword networkfailure learn 日本語。');const q=await point('.tooltip .example','learn',true);await page.mouse.move(q.x,q.y);await page.waitForTimeout(300);assert.equal(await page.evaluate(()=>window.__testShadow.querySelector('.example-panel').hidden),true);await page.evaluate(()=>{getSelection().removeAllRanges();[...window.__testShadow.querySelectorAll('.tooltip .example-token')].find(e=>e.textContent==='learn').focus();});await page.keyboard.press('Enter');await waitState('success');assert.equal(await ui('.child-word','text'),'learn');pass('Mixed English / kanji examples remain queryable; selection text is unchanged, selection suppresses hover, keyboard Enter opens a child');
 for(const zoom of [.8,1,1.5]){await page.evaluate(zoom=>document.documentElement.style.zoom=String(zoom),zoom);await page.setViewportSize({width:1200,height:900});await page.waitForTimeout(150);await inside();}
 await page.evaluate(()=>document.documentElement.style.zoom='1');await page.emulateMedia({colorScheme:'dark',reducedMotion:'reduce'});await page.setViewportSize({width:390,height:844});await page.waitForTimeout(200);await inside();await screenshot('mobile-child-dark');pass('Parent and child remain inside viewport at 80/100/150 percent CSS zoom, narrow screens, dark theme and reduced motion');
 assert.deepEqual(errors,[]);await writeFile(`${dir}/results.json`,JSON.stringify({date:new Date().toISOString(),browser:await browser.version(),results,errors,transport:'Mock AI; real bundle, IPADIC and pointer events'},null,2));
}catch(error){await screenshot('failure');console.log(await page.evaluate(()=>({parent:window.__testShadow.querySelector('.word').textContent,state:window.__testShadow.querySelector('.tooltip').dataset.state,error:window.__testShadow.querySelector('.tooltip .error').textContent,settings:window.__testShadow.querySelector('.settings .status').textContent,settingError:window.__testShadow.querySelector('.settings .error').textContent})));throw error;}finally{await browser.close();await new Promise(r=>server.close(r));}
