import {chromium} from 'playwright';import {createServer} from '../scripts/serve.mjs';import {mkdir,writeFile,readFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({channel:'msedge',headless:true}),context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();const errors=[],results=[],requests=[];page.on('pageerror',e=>errors.push(e.message));
const directory='verification/iteration-3';await mkdir(directory,{recursive:true});const pass=name=>{results.push(name);console.log('PASS',name);};
await page.addInitScript(()=>{const attach=Element.prototype.attachShadow;Element.prototype.attachShadow=function(options){const s=attach.call(this,options);if(this.hasAttribute('data-yomi-root'))window.__testShadow=s;return s;};});
const bundle=await readFile('demo/yomi-reader.js','utf8');
await page.route('**/yomi-reader.js',route=>route.fulfill({contentType:'text/javascript',body:`window.__beforeLayout=Object.fromEntries(['grammar','finance','loans','unknown-loans','compact'].map(id=>{const b=document.getElementById(id).getBoundingClientRect();return [id,{x:b.x,y:b.y,width:b.width,height:b.height}]}));\n${bundle}`}));
const ui=(selector,action='click',value)=>page.evaluate(({selector,action,value})=>{const el=window.__testShadow.querySelector(selector);if(!el)throw Error(selector);if(action==='click')el.click();if(action==='value')el.value=value;if(action==='checked')el.checked=value;if(action==='text')return el.textContent;if(action==='hidden')return el.hidden;if(action==='attribute')return el.getAttribute(value);if(action==='input'){el.value=value;el.dispatchEvent(new Event('input',{bubbles:true}));}},{selector,action,value});
const clickLabel=label=>page.evaluate(label=>{const button=[...window.__testShadow.querySelectorAll('button')].find(b=>b.textContent===label);if(!button)throw Error(label);button.click();},label);
async function point(selector,word,index=0){await page.locator(selector).scrollIntoViewIfNeeded();await page.waitForTimeout(90);return page.locator(selector).evaluate((e,{word,index})=>{let text='';const pieces=[],w=document.createTreeWalker(e,NodeFilter.SHOW_TEXT,{acceptNode:n=>n.parentElement.closest('rt,rp')?NodeFilter.FILTER_REJECT:NodeFilter.FILTER_ACCEPT});while(w.nextNode()){pieces.push({node:w.currentNode,start:text.length});text+=w.currentNode.nodeValue;}const at=text.indexOf(word)+index;if(at<0)throw Error(word);const p=[...pieces].reverse().find(p=>p.start<=at),r=document.createRange();r.setStart(p.node,at-p.start);r.setEnd(p.node,at-p.start+1);const b=r.getBoundingClientRect();return {x:(b.left+b.right)/2,y:(b.top+b.bottom)/2};},{word,index});}
const waitWord=word=>page.waitForFunction(word=>{const s=window.__testShadow;return !s.querySelector('.tooltip').hidden&&s.querySelector('.word').textContent===word;},word);
async function hover(selector,word,{fresh=true,index=0,expected=word}={}){if(fresh){await page.keyboard.press('Escape');await page.mouse.move(3,3);await page.waitForTimeout(230);}const p=await point(selector,word,index);await page.mouse.move(p.x,p.y);await waitWord(expected);return p;}
const screenshot=async name=>{await page.waitForTimeout(260);await page.screenshot({path:`${directory}/${name}.png`});};
const active=()=>page.evaluate(()=>[...(CSS.highlights.get('yomi-active')||[])].map(r=>r.toString()).join(''));
const rect=selector=>page.locator(selector).evaluate(e=>{const b=e.getBoundingClientRect();return {x:b.x,y:b.y,width:b.width,height:b.height};});
const inside=async selector=>assert.ok(await page.evaluate(selector=>{const b=window.__testShadow.querySelector(selector).getBoundingClientRect(),v=visualViewport;return b.left>=v.offsetLeft-1&&b.top>=v.offsetTop-1&&b.right<=v.offsetLeft+v.width+1&&b.bottom<=v.offsetTop+v.height+1;},selector),`${selector} exceeds viewport`);
async function configureAI(){await ui('.launcher');await ui('[data-tab=ai]');await ui('[name=aiEnabled]','checked',true);await ui('[name=endpoint]','value',base+'/mock/chat/completions');await ui('[name=model]','value','test-only');await ui('[name=sendContext]','checked',true);await ui('.save');await ui('.settings .close');}
await page.route('**/mock/chat/completions',async route=>{const body=JSON.parse(route.request().postDataJSON().messages[1].content);requests.push(body);const word=body.word;
 if(word==='networkfailure'){await route.abort('failed');return;}
 if(word==='slowword')await new Promise(r=>setTimeout(r,1400));if(word==='ネブラフラックス')await new Promise(r=>setTimeout(r,500));
 const entry={meaning:`${word} 的测试释义`,sourceWord:word==='ゼノブリッジ'?'xenobridge':word==='ルミナフォージ'?'luminforge':'解释'.repeat(500),sourceWordConfidence:word==='ゼノブリッジ'?.2:.98,etymologyKind:'borrowed',explanation:'完整说明'.repeat(250),usage:'仅用于验证渲染边界的测试数据，不是真实词源。',pos:'测试词条'};
 try{await route.fulfill({json:{choices:[{message:{content:JSON.stringify(entry)}}]}});}catch{/* Transport was correctly aborted by a newer hover. */}
});
try{
 await page.goto(base+'/learning.html');await page.waitForFunction(()=>document.querySelector('#finance rt'),null,{timeout:60000});await page.waitForTimeout(350);
 for(const id of ['grammar','finance','loans','unknown-loans','compact'])assert.deepEqual(await rect('#'+id),await page.evaluate(id=>window.__beforeLayout[id],id),`initial annotation shifted ${id}`);
 assert.equal(await page.locator('#compact rt').count(),0);pass('Initial annotations and grammar markers preserve paragraph dimensions; tight lines avoid inserting inline ruby');
 await hover('#grammar','ものの');assert.equal(await active(),'ものの');assert.match(await ui('.language','text'),/GRAMMAR/);assert.match(await ui('.meaning','text'),/虽然/);await ui('.details summary');await screenshot('grammar-card-light');
 const initialOpen=Number(await ui('.tooltip','attribute','data-open-count')),panelPoint=await page.evaluate(()=>{const b=window.__testShadow.querySelector('.tooltip .bar').getBoundingClientRect();return {x:b.x+20,y:b.y+10};});await page.mouse.move(panelPoint.x,panelPoint.y);await page.waitForTimeout(350);assert.equal(await active(),'ものの');
 await hover('#grammar','個人消費',{fresh:false});assert.equal(Number(await ui('.tooltip','attribute','data-open-count')),initialOpen);assert.equal(await active(),'個人消費');
 pass('Whole grammar active range persists inside the panel; switching to compound vocabulary does not replay panel slide');
 for(const index of [0,3,5]){await hover('#necessity','ざるを得ない',{index});assert.equal(await active(),'ざるを得ない');assert.match(await ui('.meaning','text'),/不得不/);}
 await hover('#split-grammar','ざるを得ない',{index:5});assert.equal(await active(),'ざるを得ない');assert.equal(await page.locator('#split-grammar strong').count(),1);await page.keyboard.press('Escape');await page.waitForTimeout(220);await page.locator('#grammar-link').click();assert.equal(await page.evaluate(()=>window.linkClicks),1);
 await hover('#split-compound','データセンター',{index:5});assert.equal(await active(),'データセンター');assert.match(await ui('.reading','text'),/data center/);pass('All portions of grammar and split katakana compounds target the full expression; inline link handlers survive');
 await page.keyboard.press('Escape');await page.locator('#append').click();await page.waitForFunction(()=>document.querySelector('#dynamic [data-yomi-grammar]'));await hover('#dynamic','ものの');assert.equal(await active(),'ものの');const count=await page.locator('[data-yomi-token]').count();await page.waitForTimeout(300);assert.equal(await page.locator('[data-yomi-token]').count(),count);pass('Dynamic grammar markers are incremental and do not cause observer loops');
 await hover('#unknown-loans','ネブラフラックス');assert.equal(await ui('.tooltip','attribute','data-state'),'empty');await clickLabel('AI 解释 ↗');assert.match(await ui('.tooltip .error','text'),/尚未配置/);
 await configureAI();await hover('#unknown-loans','ネブラフラックス');assert.equal(await ui('.tooltip','attribute','data-state'),'loading');const before=await rect('#unknown-loans');await screenshot('loading');await page.waitForFunction(()=>window.__testShadow.querySelector('.tooltip').dataset.state==='success');assert.deepEqual(await rect('#unknown-loans'),before);assert.equal(await page.locator('#unknown-loans rt').count(),0);await ui('.details summary');assert.ok((await ui('.usage','text')).length>=1000);assert.ok(!(await page.locator('#unknown-loans').textContent()).includes('完整说明'));await screenshot('long-response-contained');
 await hover('#unknown-loans','ゼノブリッジ');await page.waitForFunction(()=>window.__testShadow.querySelector('.tooltip').dataset.state==='success');assert.equal(await page.locator('#unknown-loans rt').count(),0);
 await hover('#unknown-loans','ルミナフォージ');const safeBefore=await rect('#unknown-loans');await page.waitForFunction(()=>document.querySelector('#unknown-loans rt')?.textContent==='luminforge');assert.deepEqual(await rect('#unknown-loans'),safeBefore);assert.equal(await active(),'ルミナフォージ');pass('1000-character API fields stay in the panel; low confidence is never annotated; trusted short source adds no reflow or lost active range');
 await page.evaluate(()=>{document.getElementById('race').style.cssText='display:flex;flex-direction:column;gap:10px';document.getElementById('race').replaceChildren(...['slowword','fastword','networkfailure','finalword'].map(word=>{const span=document.createElement('span');span.textContent=word;return span;}));});
 await hover('#race','slowword');await page.waitForFunction(()=>window.__testShadow.querySelector('.tooltip').dataset.state==='loading');await hover('#race','finalword',{fresh:false});await page.waitForFunction(()=>window.__testShadow.querySelector('.meaning').textContent.includes('finalword 的'));await page.waitForTimeout(1500);assert.equal(await ui('.word','text'),'finalword');
 await hover('#race','networkfailure');await page.waitForFunction(()=>window.__testShadow.querySelector('.tooltip').dataset.state==='error');await screenshot('network-error');await hover('#finance','金融政策');assert.match(await ui('.meaning','text'),/货币政策/);pass('Canceled slow request cannot replace the last active word; network errors remain local and dictionary queries work');
 await hover('#inflected','踏まえる');await clickLabel('＋ 收录');await page.waitForFunction(()=>!window.__testShadow.querySelector('.collection-picker').hidden);await ui('.collection-save');await page.waitForFunction(()=>window.__testShadow.querySelector('.learning-status').textContent.includes('第 1 次'));await screenshot('collected-word');
 await hover('#necessity','ざるを得ない');await clickLabel('＋ 收录');await page.waitForFunction(()=>!window.__testShadow.querySelector('.collection-picker').hidden);await ui('.collection-save');await page.waitForFunction(()=>window.__testShadow.querySelector('.learning-status').textContent.includes('已收录'));
 await hover('#grammar','ものの');await clickLabel('＋ 收录');await page.waitForFunction(()=>!window.__testShadow.querySelector('.collection-picker').hidden);await ui('.collection-save');await page.waitForFunction(()=>window.__testShadow.querySelector('.learning-status').textContent.includes('已收录'));await ui('.library-launch');assert.equal(await ui('.library .library-count','text').then(t=>/3 条/.test(t)),true);await screenshot('library');
 await ui('.library-search','input','consider');await page.waitForTimeout(250);assert.match(await ui('.library-results','text'),/踏まえる/);await ui('.library-search','input','');await page.waitForTimeout(250);
 await page.goto(base+'/learning.html?visit=second');await page.waitForFunction(()=>document.querySelector('#finance rt'),null,{timeout:60000});await hover('#inflected','踏まえる');await page.waitForFunction(()=>window.__testShadow.querySelector('.learning-status').textContent.includes('第 2 次'));await hover('#inflected','踏まえる');await page.waitForTimeout(100);assert.match(await ui('.learning-status','text'),/第 2 次/);pass('Vocabulary and complete grammar collect in one click; IndexedDB reload restores them; second URL is one encounter without duplicate item');
 await ui('.library-launch');await ui('.review-tab');await screenshot('review-dashboard');await ui('.quiz-mode','value','cloze');await ui('.start-review');await page.waitForFunction(()=>!window.__testShadow.querySelector('.quiz-view').hidden);assert.match(await ui('.quiz-prompt','text'),/＿＿＿＿/);assert.match(await ui('.quiz-origin','text'),/learning.html/);await ui('.reveal');await screenshot('review-cloze');await ui('.grade-actions button:nth-child(3)');await page.waitForTimeout(250);
 const saved=await page.evaluate(async()=>{const keys=await GM.listValues(),itemKeys=keys.filter(k=>k.startsWith('yomi:library:v1:item:'));return Promise.all(itemKeys.map(k=>GM.getValue(k)));});assert.equal(saved.length,3);const reviewed=saved.find(i=>i.reviewCount===1);assert.ok(reviewed);assert.equal(reviewed.currentInterval,1);assert.equal(reviewed.correctCount,1);assert.ok(reviewed.nextReviewAt>Date.now());assert.equal(reviewed.encounterCount,2);
 const records=await page.evaluate(async id=>GM.getValue('yomi:library:v1:reviews:'+id+':0'),reviewed.id);assert.equal(records[0].grade,'good');assert.equal(records[0].quiz.mode,'cloze');assert.ok(saved.some(i=>i.grammarPattern==='～ざるを得ない'));pass('Review uses the actual saved sentence; grading persists schedule, counters and ReviewRecord independently of encounters');
 await ui('.library-tab');await ui('.library-edit');await page.waitForFunction(()=>!window.__testShadow.querySelector('.library-detail').hidden);await ui('[data-edit=tags]','value','金融, IT');await ui('[data-edit=notes]','value','真实语境的重要表达');await clickLabel('保存修改');await page.waitForFunction(()=>[...window.__testShadow.querySelectorAll('button')].some(b=>b.textContent==='已保存'));await screenshot('library-detail');
 await page.keyboard.press('Escape');await ui('.launcher');await ui('[name=theme]','value','dark');await ui('.save');await screenshot('settings-dark');await ui('.settings .close');await page.evaluate(()=>document.body.classList.add('dark'));await hover('#grammar','ものの');await screenshot('grammar-card-dark');
 for(const zoom of [.8,1,1.25,1.75]){await page.keyboard.press('Escape');await page.waitForTimeout(220);await page.evaluate(z=>document.documentElement.style.zoom=String(z),zoom);await hover('#edge','power');await inside('.tooltip');await ui('.library-launch');await inside('.library');}
 await page.keyboard.press('Escape');await page.evaluate(()=>document.documentElement.style.zoom='1');await page.setViewportSize({width:390,height:844});await ui('.library-launch');await inside('.library');await screenshot('library-mobile');await page.keyboard.press('Escape');await page.emulateMedia({reducedMotion:'reduce'});await hover('#grammar','ものの');assert.equal(await page.evaluate(()=>window.__testShadow.querySelector('.tooltip').getAnimations().length),0);pass('Light/dark, 80–175% CSS zoom, 390px viewport and reduced-motion settings retain usable overlay layout');
 await page.keyboard.press('Escape');await page.setViewportSize({width:1440,height:1000});await page.evaluate(()=>{window.__originalSetValue=GM.setValue;GM.setValue=(key,value)=>key.startsWith('yomi:library:')?Promise.reject(new Error('test storage unavailable')):window.__originalSetValue(key,value);});await hover('#finance','金融政策');await clickLabel('＋ 收录');await page.waitForFunction(()=>!window.__testShadow.querySelector('.collection-picker').hidden);await ui('.collection-save');await page.waitForFunction(()=>window.__testShadow.querySelector('.collection-error').textContent.includes('test storage unavailable'));assert.match(await ui('.meaning','text'),/货币政策/);await page.evaluate(()=>GM.setValue=window.__originalSetValue);await ui('.collection-cancel');await hover('#loans','エージェント');assert.match(await ui('.meaning','text'),/智能体/);pass('Injected persistence failure is visible on the card without disabling basic dictionary or reading interactions');
 assert.deepEqual(errors,[]);await writeFile(`${directory}/results.json`,JSON.stringify({date:new Date().toISOString(),browser:await browser.version(),results,errors,requests:requests.map(({word,context})=>({word,context})),scope:'Actual bundled userscript + real IPADIC + real demo IndexedDB; AI transport mocked; browser-manager cross-origin GM not exercised'},null,2));
}catch(e){console.error(e);console.error(await page.evaluate(()=>({word:window.__testShadow?.querySelector('.word')?.textContent,active:[...(CSS.highlights?.get('yomi-active')||[])].map(r=>r.toString()),error:window.__testShadow?.querySelector('.library-error')?.textContent,status:window.__testShadow?.querySelector('.status')?.textContent})));await page.screenshot({path:`${directory}/failure.png`,fullPage:true});throw e;}finally{await browser.close();await new Promise(r=>server.close(r));}
