import {chromium} from 'playwright';import {createServer} from '../scripts/serve.mjs';import {readFile,mkdir,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1400,height:1050}}),results=[],errors=[],dir='verification/precision';await mkdir(dir,{recursive:true});page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{const attach=Element.prototype.attachShadow;Element.prototype.attachShadow=function(o){const s=attach.call(this,o);if(this.hasAttribute('data-yomi-root'))window.ui=s;return s;};});
const bundle=await readFile('demo/yomi-reader.js','utf8');await page.route('**/yomi-reader.js',r=>r.fulfill({contentType:'text/javascript',body:`window.before=[...document.querySelectorAll('#news li')].map(e=>e.getBoundingClientRect().toJSON());\n${bundle}`}));
const pass=s=>{results.push(s);console.log('PASS',s);};
async function inspect(){return page.evaluate(()=>({boxes:[...document.querySelectorAll('#news li')].map(e=>e.getBoundingClientRect().toJSON()),fonts:[...document.querySelectorAll('#news a [data-yomi-annotation]')].filter(e=>getComputedStyle(e).display!=='none').map(e=>parseFloat(getComputedStyle(e).fontSize)),padding:[...document.querySelectorAll('#news li')].map(e=>e.style.paddingTop)}));}
async function hover(selector,word){await page.locator(selector).scrollIntoViewIfNeeded();const p=await page.locator(selector).evaluate((el,word)=>{const w=document.createTreeWalker(el,NodeFilter.SHOW_TEXT,{acceptNode:n=>n.parentElement.closest('[data-yomi-ui],rt')?NodeFilter.FILTER_REJECT:NodeFilter.FILTER_ACCEPT});while(w.nextNode()){const at=w.currentNode.nodeValue.indexOf(word);if(at<0)continue;const r=document.createRange();r.setStart(w.currentNode,at);r.setEnd(w.currentNode,at+1);const b=r.getBoundingClientRect();return {x:b.x+b.width/2,y:b.y+b.height/2};}},word);await page.mouse.move(p.x,p.y);await page.waitForFunction(word=>ui.querySelector('.word').textContent===word,word);await page.waitForTimeout(100);}
const action=s=>page.evaluate(s=>ui.querySelector(s).click(),s);
try{
 await page.goto(base+'/precision.html');await page.waitForFunction(()=>document.querySelectorAll('#news [data-yomi-annotation]').length>30,null,{timeout:60000});await page.waitForTimeout(400);
 const before=await page.evaluate(()=>window.before),initial=await inspect();initial.boxes.forEach((b,i)=>assert.equal(b.height,before[i].height));assert.ok(initial.fonts.length>25);for(const size of initial.fonts)assert.ok(Math.abs(size-16.5)<.1);assert.ok(initial.padding.every(p=>!p));await page.screenshot({path:dir+'/compact-list.png'});pass('Mixed-size badges and side-column text do not enlarge single-line list items; all 30px-source annotations use the same 16.5px font');
 const fit=await page.evaluate(()=>{const labels=[...document.querySelectorAll('#news a [data-yomi-annotation]')].filter(e=>getComputedStyle(e).display!=='none'),boxes=labels.map(e=>e.getBoundingClientRect());let collisions=0;for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++){const a=boxes[i],b=boxes[j];if(a.left<b.right-.5&&a.right>b.left+.5&&a.top<b.bottom-.5&&a.bottom>b.top+.5)collisions++;}return {count:labels.length,full:labels.filter(e=>e.scrollWidth<=e.clientWidth+1).length,collisions};});assert.equal(fit.collisions,0);assert.ok(fit.full/fit.count>.9);pass('Horizontal space borrowing keeps over 90% of fixture readings complete at the uniform font size, with no annotation-to-annotation collisions');
 for(let n=0;n<5;n++){await page.evaluate(n=>document.querySelector('#news').dataset.tick=n,n);await page.setViewportSize({width:1380+n%2*20,height:1050});await page.waitForTimeout(100);}
 const stable=await inspect();stable.boxes.forEach((b,i)=>assert.equal(b.height,initial.boxes[i].height));pass('Repeated mutations and resize passes do not accumulate line-height or padding');
 await hover('#english','learned');await action('.tooltip .details summary');
 const data=await page.evaluate(()=>({source:ui.querySelector('.source-sentence').textContent,senses:[...ui.querySelectorAll('.tooltip .sense')].map(e=>({title:e.querySelector('h4').textContent,examples:[...e.querySelectorAll('.example')].map(e=>e.textContent)})),marked:ui.querySelectorAll('.tooltip [data-context-match=true]').length}));
 assert.equal(data.source,'I learned that the train had been delayed.');assert.equal(data.senses.length,2);assert.equal(data.marked,0);assert.ok(data.senses.every(s=>s.examples.length===2&&!s.examples.includes(data.source)));await page.screenshot({path:dir+'/senses.png'});pass('Actual source sentence is separate from two local senses with two examples each; no unsupported context-match claim');
 await page.evaluate(()=>{const scroller=ui.querySelector('.tip-scroll'),sense=ui.querySelectorAll('.tooltip .sense')[1];scroller.scrollTop+=sense.getBoundingClientRect().top-scroller.getBoundingClientRect().top-80;});await page.screenshot({path:dir+'/second-sense.png'});
 await action('.tooltip .sense:nth-of-type(2) .example-token');await page.waitForFunction(()=>!ui.querySelector('.example-panel').hidden);pass('Examples under a later sense support nested word lookup');
 await page.keyboard.press('Escape');await page.keyboard.press('Escape');await page.waitForTimeout(230);
 await action('.launcher');await action('[data-tab=ai]');await page.evaluate(base=>{ui.querySelector('[name=aiEnabled]').checked=true;ui.querySelector('[name=sendContext]').checked=true;ui.querySelector('[name=endpoint]').value=base+'/mock/chat/completions';ui.querySelector('[name=model]').value='deepseek-flash';},base);await action('.save');await action('.settings .close');
 const sent=[];await page.route('**/mock/chat/completions',r=>{sent.push(r.request().postDataJSON());return r.fulfill({json:{choices:[{message:{content:JSON.stringify({meaning:'得知',contextMeaning:'原句表示得知火车晚点的消息。',senses:[{meaning:'学习',usage:'learn to do',contextMatch:false,examples:[{text:'I learn Japanese.',translation:'我学日语。'},{text:'They learn to swim.',translation:'他们学游泳。'}]},{meaning:'得知',usage:'learn that',contextMatch:true,examples:[{text:'I learned that it was closed.',translation:'我得知它关闭了。'},{text:'We learned of the change.',translation:'我们得知了变动。'}]}]})}}]}});});
 await hover('#english','learned');await page.evaluate(()=>[...ui.querySelectorAll('.tooltip .actions button')].find(e=>e.textContent.includes('AI')).click());await page.waitForFunction(()=>ui.querySelector('.context-meaning').textContent.includes('火车'));await page.evaluate(()=>{ui.querySelector('.tooltip .details').open=true;ui.querySelector('.tip-scroll').scrollTop=0;});assert.equal(await page.evaluate(()=>ui.querySelectorAll('.tooltip [data-context-match=true]').length),1);assert.ok(JSON.parse(sent[0].messages[1].content).context.includes('train'));assert.ok(sent[0].messages[0].content.includes('至少两条'));await page.screenshot({path:dir+'/context-senses.png'});pass('Structured AI response renders sense-specific examples and contextual match separately from original text, using bounded opt-in context');
 assert.deepEqual(errors,[]);await writeFile(dir+'/results.json',JSON.stringify({date:new Date().toISOString(),browser:await browser.version(),results,errors},null,2));
}catch(e){await page.screenshot({path:dir+'/failure.png'});throw e;}finally{await browser.close();await new Promise(r=>server.close(r));}
