import {chromium} from 'playwright';import {createServer} from '../scripts/serve.mjs';import {readFile,mkdir,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1280,height:1000}}),errors=[],results=[],dir='verification/scrolling';await mkdir(dir,{recursive:true});page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{const attach=Element.prototype.attachShadow;Element.prototype.attachShadow=function(o){const s=attach.call(this,o);if(this.hasAttribute('data-yomi-root'))window.ui=s;return s;};});
const bundle=await readFile('demo/yomi-reader.js','utf8');await page.route('**/yomi-reader.js',r=>r.fulfill({contentType:'text/javascript',body:`window.before=Object.fromEntries(['headline','caption','flow','tight','scroller'].map(id=>[id,document.getElementById(id).getBoundingClientRect().toJSON()]));\n${bundle}`}));
const pass=s=>{results.push(s);console.log('PASS',s);};
const checks=()=>page.evaluate(()=>{const areas=['headline','caption','flow','tight','nested'],collisions=[],counts={};for(const id of areas){const root=document.getElementById(id),w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode:n=>n.parentElement.closest('[data-yomi-ui],rt,rp')?NodeFilter.FILTER_REJECT:NodeFilter.FILTER_ACCEPT}),glyphs=[];while(w.nextNode()){const r=document.createRange();r.selectNodeContents(w.currentNode);glyphs.push(...r.getClientRects());}const labels=[...root.querySelectorAll('[data-yomi-annotation]')].filter(e=>getComputedStyle(e).display!=='none');counts[id]=labels.length;for(const label of labels){const b=label.getBoundingClientRect();for(const g of glyphs)if(b.left<g.right-.5&&b.right>g.left+.5&&b.top<g.bottom-.5&&b.bottom>g.top+.5)collisions.push({id,text:label.textContent,b:b.toJSON(),g:g.toJSON()});}}return {counts,collisions};});
async function track(id){return page.evaluate(id=>{const root=document.getElementById(id),label=[...root.querySelectorAll('[data-yomi-annotation]')].find(e=>getComputedStyle(e).display!=='none'),host=label.parentElement;let node=host.nextSibling;while(node&&node.nodeType!==3)node=node.nextSibling;if(!node)throw Error('No source');const range=document.createRange();range.setStart(node,0);range.setEnd(node,Math.min(1,node.length));window.track={label,range};const b=label.getBoundingClientRect(),g=range.getBoundingClientRect();return {dx:b.x-g.x,dy:b.y-g.y};},id);}
try{
 await page.goto(base+'/scrolling.html');await page.waitForFunction(()=>document.querySelectorAll('[data-yomi-annotation]').length>35,null,{timeout:60000});await page.waitForTimeout(600);
 for(const id of ['headline','caption','flow','tight','scroller']){const now=await page.locator('#'+id).evaluate(e=>e.getBoundingClientRect().toJSON()),old=await page.evaluate(id=>before[id],id);assert.equal(now.width,old.width);assert.equal(now.x,old.x);if(id==='flow')assert.equal(now.height,old.height);if(id==='headline'||id==='tight')assert.ok(now.height>old.height&&now.height<old.height+140);}let report=await checks();assert.deepEqual(report.collisions,[]);assert.ok(report.counts.flow>6&&report.counts.headline>5);await page.screenshot({path:`${dir}/multiline.png`});pass('Only crowded text blocks gain local leading; widths and sufficient-spacing paragraphs stay unchanged; visible labels do not overlap source glyph boxes');
 assert.equal(await page.locator('#headline [data-surface="投稿"]').count(),1);
 const initial=await track('flow');const deltas=await page.evaluate(()=>{const result=[];for(const y of [80,180,300,120,0]){scrollTo(0,y);const b=track.label.getBoundingClientRect(),g=track.range.getBoundingClientRect();result.push({dx:b.x-g.x,dy:b.y-g.y});}return result;});for(const d of deltas){assert.ok(Math.abs(d.dx-initial.dx)<1&&Math.abs(d.dy-initial.dy)<1);}pass('Window scroll maintains annotation/source offsets synchronously in the same JS task, with no scroll event or animation-frame wait');
 await page.locator('#scroller').scrollIntoViewIfNeeded();await page.waitForTimeout(100);const nested=await track('nested');const nestedDeltas=await page.evaluate(()=>{const out=[];for(const y of [30,85,160,0]){document.getElementById('scroller').scrollTop=y;const b=track.label.getBoundingClientRect(),g=track.range.getBoundingClientRect();out.push({dx:b.x-g.x,dy:b.y-g.y});}return out;});for(const d of nestedDeltas)assert.ok(Math.abs(d.dx-nested.dx)<1&&Math.abs(d.dy-nested.dy)<1);pass('Nested scroll container uses the same native motion as its text, without a JavaScript follow-up');
 await page.evaluate(()=>scrollTo(0,0));await page.setViewportSize({width:780,height:1000});await page.waitForTimeout(500);report=await checks();assert.deepEqual(report.collisions,[]);await page.screenshot({path:`${dir}/narrow-lines.png`});pass('Rewrapping at a narrower width recomputes per-line placement and collision limits');
 await page.evaluate(()=>document.documentElement.style.zoom='1.25');await page.waitForTimeout(500);assert.deepEqual((await checks()).collisions,[]);await page.evaluate(()=>{document.documentElement.style.zoom='1';document.querySelector('#tight').style.lineHeight='2.1';});await page.waitForTimeout(500);assert.deepEqual((await checks()).collisions,[]);pass('CSS zoom and dynamic line-height changes recompute safe annotation geometry');
 await page.evaluate(()=>{ui.querySelector('.launcher').click();ui.querySelector('[name=annotationEnabled]').checked=false;ui.querySelector('.save').click();});await page.waitForTimeout(250);assert.equal(await page.locator('[data-yomi-annotation-anchor]').count(),0);assert.equal(await page.locator('#headline').evaluate(e=>e.style.lineHeight),'');assert.equal(await page.locator('#tight').evaluate(e=>e.style.lineHeight),'2.1');pass('Disabling annotations removes anchors and restores owned spacing while preserving a subsequent site-authored line-height change');
 assert.deepEqual(errors,[]);await writeFile(`${dir}/results.json`,JSON.stringify({date:new Date().toISOString(),browser:await browser.version(),results,errors},null,2));
}catch(e){console.log(JSON.stringify(await checks()).slice(0,3000));await page.screenshot({path:`${dir}/failure.png`});throw e;}finally{await browser.close();await new Promise(r=>server.close(r));}
