import {chromium} from 'playwright';import {createServer} from '../scripts/serve.mjs';import {mkdir,readFile,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),results=[],errors=[];const dir='verification/windows';await mkdir(dir,{recursive:true});page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{const attach=Element.prototype.attachShadow;Element.prototype.attachShadow=function(o){const s=attach.call(this,o);if(this.hasAttribute('data-yomi-root'))window.ui=s;if(this.hasAttribute('data-yomi-annotation-layer'))window.annotations=s;return s;};});
const bundle=await readFile('demo/yomi-reader.js','utf8');await page.route('**/yomi-reader.js',r=>r.fulfill({contentType:'text/javascript',body:`window.before=document.querySelector('#nav').outerHTML;window.beforeRects=Object.fromEntries(['nav','nav-loan','heading','grammar'].map(id=>[id,document.getElementById(id).getBoundingClientRect().toJSON()]));\n${bundle}`}));
const rect=s=>page.evaluate(s=>ui.querySelector(s).getBoundingClientRect().toJSON(),s),text=s=>page.evaluate(s=>ui.querySelector(s).textContent,s);
async function click(s){await page.evaluate(s=>ui.querySelector(s).scrollIntoView({block:'nearest'}),s);await page.waitForTimeout(100);const b=await rect(s);await page.mouse.click(b.x+b.width/2,b.y+b.height/2);await page.waitForTimeout(220);}
async function drag(s,dx,dy){const b=await rect(s);await page.mouse.move(b.x+45,b.y+22);await page.mouse.down();await page.mouse.move(b.x+45+dx,b.y+22+dy,{steps:12});await page.mouse.up();await page.waitForTimeout(120);}
async function resize(s,edge,dx,dy){const b=await rect(s+` [data-edge="${edge}"]`);await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width/2+dx,b.y+b.height/2+dy,{steps:12});await page.mouse.up();await page.waitForTimeout(160);}
async function hover(s,word,owned=false){await page.evaluate(({s,owned})=>(owned?ui:document).querySelector(s).scrollIntoView({block:'nearest'}),{s,owned});await page.waitForTimeout(230);const p=await page.evaluate(({s,word,owned})=>{const el=(owned?ui:document).querySelector(s),w=document.createTreeWalker(el,NodeFilter.SHOW_TEXT,{acceptNode:n=>n.parentElement.closest('rt')?NodeFilter.FILTER_REJECT:NodeFilter.FILTER_ACCEPT});let raw='',nodes=[];while(w.nextNode()){nodes.push({n:w.currentNode,start:raw.length});raw+=w.currentNode.nodeValue;}const at=raw.indexOf(word),part=nodes.findLast(p=>p.start<=at);const r=document.createRange();r.setStart(part.n,at-part.start);r.setEnd(part.n,at-part.start+1);const b=r.getBoundingClientRect();return{x:b.x+b.width/2,y:b.y+b.height/2};},{s,word,owned});await page.mouse.move(p.x,p.y);await page.waitForFunction(({word,owned})=>ui.querySelector(owned?'.child-word':'.word').textContent===word,{word,owned});}
const pass=s=>{results.push(s);console.log('PASS',s);};
async function shot(name){await page.waitForTimeout(250);await page.screenshot({path:`${dir}/${name}.png`});}
async function fullWindow(s){assert.equal(await page.evaluate(s=>ui.querySelector(s).querySelectorAll('.window-resize').length,s),8);await drag(s,-250,-120);const a=await rect(s);await resize(s,'se',100,70);const b=await rect(s);assert.ok(b.width>a.width+50);assert.ok(b.height>a.height+30);await drag(s,3000,3000);const edge=await rect(s);assert.ok(Math.abs(edge.right-1440)<2);assert.ok(Math.abs(edge.bottom-1000)<2);await click(s+' .window-maximize');const max=await rect(s);assert.ok(max.width>=1438&&max.height>=998&&max.x<2&&max.y<2);await click(s+' .window-maximize');assert.ok(Math.abs((await rect(s)).width-b.width)<2);await drag(s,-300,-150);}
try{
 await page.goto(base+'/interactions.html');await page.waitForFunction(()=>{const labels=[...document.querySelectorAll('[data-yomi-annotation-anchor]')].map(e=>e.textContent).join(' ');return labels.includes('せいさく')&&labels.includes('power')&&labels.includes('data center');},null,{timeout:60000});assert.equal(await page.locator('#nav').evaluate(e=>{const copy=e.cloneNode(true);copy.querySelectorAll('[data-yomi-ui]').forEach(n=>n.remove());return copy.outerHTML;}),await page.evaluate(()=>before));for(const id of ['nav','nav-loan','heading','grammar'])assert.deepEqual(await page.locator('#'+id).evaluate(e=>e.getBoundingClientRect().toJSON()),await page.evaluate(id=>beforeRects[id],id));await page.locator('#nav').click();assert.equal(await page.locator('#clicks').textContent(),'1');await page.keyboard.press('Escape');await page.mouse.move(3,3);await shot('navigation-annotations');pass('Navigation visibly has kana and trusted source words before hover; button HTML, click handler and page geometry are unchanged');
 await click('.launcher');await fullWindow('.settings');const settingsRect=await rect('.settings');await click('[data-tab=ai]');assert.equal((await rect('.settings')).x,settingsRect.x);await shot('terminal-resized');await click('.settings .close');await click('.launcher');assert.equal((await rect('.settings')).width,settingsRect.width);await click('.settings .close');pass('Reading terminal supports eight-edge resize, full-viewport drag, maximize/restore and retained geometry across tabs and reopening');
 await click('.library-launch');await fullWindow('.library');const libraryRect=await rect('.library');await click('.review-tab');assert.equal((await rect('.library')).x,libraryRect.x);assert.equal((await rect('.library')).width,libraryRect.width);await shot('library-review-resized');await click('.library .close');pass('Library and Review use the same movable/resizable window and retain their geometry');
 await hover('#grammar','ものの');await fullWindow('.tooltip');await click('.tooltip .details summary');await hover('.tooltip .example','個人消費',true);await fullWindow('.example-panel');assert.equal(await text('.word'),'ものの');await shot('cards-resized');pass('Main card and example subcard both resize, drag to bottom-right edge, maximize and restore without replacing the parent query');
 await page.setViewportSize({width:390,height:844});await page.emulateMedia({colorScheme:'dark',reducedMotion:'reduce'});await page.waitForTimeout(250);for(const s of ['.tooltip','.example-panel']){const b=await rect(s);assert.ok(b.x>=-1&&b.y>=-1&&b.right<=391&&b.bottom<=845);}await click('.example-panel .window-maximize');assert.ok((await rect('.example-panel')).width>=389);await shot('mobile-maximized');pass('User-sized windows recover inside smaller viewports and maximize correctly in narrow dark reduced-motion mode');
 assert.deepEqual(errors,[]);await writeFile(`${dir}/results.json`,JSON.stringify({date:new Date().toISOString(),browser:await browser.version(),results,errors},null,2));
}catch(error){await shot('failure');console.log(errors);throw error;}finally{await browser.close();await new Promise(r=>server.close(r));}
