import {renderPronunciation} from './pronunciation.js';
import {makeQuiz,QUIZ_MODES} from './quiz.js';
import {GRADES,schedule,intervalLabel} from './scheduler.js';
import {makeDraggable} from './drag.js';
export const STATE_LABELS={new:'新收录',learning:'学习中',reviewing:'复习中',mastered:'已掌握',suspended:'已暂停'};
const date=value=>value?new Date(value).toLocaleString('zh-CN',{hour12:false}):'—';
export function createLearningUI(shadow,repo,onOpen,collection,onRead) {
  const panel=document.createElement('section');panel.className='panel library';panel.hidden=true;panel.setAttribute('role','dialog');panel.setAttribute('aria-label','学习资料库');
  panel.innerHTML=`<div class="bar"><span class="eyebrow">YOMI / PERSONAL LEARNING SYSTEM</span><button class="icon close" aria-label="关闭资料库">×</button></div>
  <div class="library-heading"><h2>学习资料库 <small>LIBRARY</small></h2><div class="actions"><button class="action primary library-tab">全部资料</button><button class="action review-tab">间隔复习 ↗</button><button class="action custom-add">＋ 自定义</button></div></div>
  <div class="library-scroll"><div class="library-error error" role="status"></div><div class="library-list-view"><div class="category-layout"><aside class="category-sidebar"><div class="label">COLLECTIONS / 分类</div><nav class="category-nav" aria-label="资料分类"></nav><button class="action manage-categories">管理分类</button></aside><div class="category-main"><div class="category-manager" hidden></div><div class="row"><label class="field">搜索<input class="library-search" placeholder="词语、中文、词源、标签或原句"></label><label class="field">筛选<select class="library-filter"><option value="all">全部</option><option value="vocabulary">词汇</option><option value="grammar">语法</option><option>N1</option><option>N2</option><option value="loanword">外来语</option><option value="english">英语</option><option value="custom">自定义</option><option value="due">待复习</option><option value="mastered">已掌握</option></select></label></div><div class="library-count note"></div><div class="library-results"></div><div class="actions"><button class="action previous">上一页</button><button class="action next">下一页</button><button class="action repair">修复存储索引</button></div></div></div></div>
  <div class="library-detail" hidden></div><div class="review-view" hidden><div class="review-stats"></div><label class="field">复习题型<select class="quiz-mode"></select></label><button class="action primary start-review">开始复习</button><div class="quiz-view" hidden><div class="quiz-progress note"></div><div class="quiz-prompt"></div><div class="quiz-choices actions"></div><div class="quiz-origin note"></div><div class="quiz-note note"></div><button class="action reveal">显示答案</button><div class="quiz-answer" hidden></div><div class="quiz-pronunciation pronunciation" hidden></div><button class="action quiz-card" hidden>查看完整资料卡</button><div class="grade-actions actions" hidden></div></div></div></div>`;
  shadow.querySelector('.surface').append(panel);const $=s=>panel.querySelector(s);let category='all',offset=0,tab='library',queue=[],quiz,current,detailID,searchTimer,runVersion=0;
  const windowControl=makeDraggable(panel,$('.bar'));
  function position(){if(panel.hidden||windowControl.isDragging())return;if(windowControl.hasGeometry()){windowControl.reflow();return;}const v=visualViewport||{offsetLeft:0,offsetTop:0,width:innerWidth,height:innerHeight};panel.style.maxWidth=v.width+'px';panel.style.maxHeight=v.height+'px';panel.style.right='auto';panel.style.left=Math.max(v.offsetLeft,v.offsetLeft+v.width-panel.offsetWidth-24)+'px';panel.style.top=Math.max(v.offsetTop,Math.min(v.offsetTop+24,v.offsetTop+v.height-panel.offsetHeight))+'px';}
  new ResizeObserver(position).observe(panel);
  const put=(s,v)=>$(s).textContent=v;
  const node=(tag,text,className)=>{const n=document.createElement(tag);n.textContent=text;if(className)n.className=className;return n;};
  function error(e){put('.library-error',e?.message||String(e));}
  async function run(fn){put('.library-error','');try{await fn();}catch(e){error(e);}}
  function stats(){const items=[...repo.items.values()],now=Date.now();put('.review-stats',`今日待复习 ${items.filter(i=>i.state!=='suspended'&&i.state!=='new'&&i.nextReviewAt<=now).length}　/　今日新词 ${Math.min(20,items.filter(i=>i.state==='new'&&i.nextReviewAt<=now).length)}\n学习中 ${items.filter(i=>i.state==='learning').length}　/　复习中 ${items.filter(i=>i.state==='reviewing').length}`);}
  function list(){if(panel.hidden||tab!=='library'||detailID)return;categories();const data=repo.query({category,search:$('.library-search').value,filter:$('.library-filter').value,offset});put('.library-count',`${data.total} 条资料 · ${data.total?offset+1:0}–${offset+data.items.length} · 阅读中的再次遇见与正式复习分别计数`);const target=$('.library-results');target.replaceChildren();for(const item of data.items){const b=node('button','','library-item');b.append(node('strong',item.expression),node('span',item.meaningZh),node('small',`${item.type} ${item.jlptLevel} · ${STATE_LABELS[item.state]} · 遇见 ${item.encounterCount} · 复习 ${item.reviewCount}`));const names=repo.categoryIds(item).map(id=>repo.categoryList().find(c=>c.id===id)?.name).filter(Boolean);b.append(node('small',names.join(' · ')||'未分类','item-categories'));b.onclick=()=>run(async()=>{await onRead(item.id);panel.hidden=true;});const row=node('div','','library-row'),edit=node('button','编辑','action library-edit');edit.setAttribute('aria-label','编辑 '+item.expression);edit.onclick=()=>run(()=>detail(item.id));row.append(b,edit);target.append(row);}if(!data.total)target.append(node('p','还没有符合条件的资料。阅读时打开词卡，点击「＋ 收录」。','note'));$('.previous').disabled=offset===0;$('.next').disabled=offset+40>=data.total;}
  function categories(){
    if(category!=='all'&&category!=='unfiled'&&!repo.categoryList().some(c=>c.id===category))category='all';
    const {counts,unfiled}=repo.categoryCounts(),nav=$('.category-nav');nav.replaceChildren();
    for(const row of [{id:'all',name:'全部资料',count:repo.items.size},{id:'unfiled',name:'未分类',count:unfiled},...repo.categoryList().map(c=>({...c,count:counts.get(c.id)||0}))]){const b=node('button','','category-link');b.dataset.category=row.id;b.setAttribute('aria-pressed',String(category===row.id));b.append(node('span',row.name),node('small',String(row.count)));b.onclick=()=>{category=row.id;offset=0;list();};nav.append(b);}
  }
  function manager(){const box=$('.category-manager');box.replaceChildren();box.append(node('h3','管理分类'),node('p','分类可以是语言、主题或项目。删除分类保留全部资料和复习进度。','note'));
    const create=node('div','','category-create'),input=document.createElement('input');input.className='category-new-name';input.maxLength=40;input.placeholder='例如：韩语 / 金融 / 工作';input.setAttribute('aria-label','新增分类名称');const add=node('button','＋ 新建','action');add.onclick=()=>run(async()=>{add.disabled=true;try{await repo.createCategory(input.value);manager();list();}finally{add.disabled=false;}});input.onkeydown=e=>{if(e.key==='Enter')add.click();};create.append(input,add);box.append(create);
    for(const c of repo.categoryList()){const row=node('div','','category-manage-row'),name=document.createElement('input');name.value=c.name;name.maxLength=40;name.setAttribute('aria-label','重命名 '+c.name);row.dataset.id=c.id;const rename=node('button','改名','action'),remove=node('button','移除','action');rename.onclick=()=>run(async()=>{await repo.changeCategory(c.id,name.value);manager();list();});remove.onclick=()=>run(async()=>{await repo.deleteCategory(c.id);manager();list();});row.append(name,rename,remove);box.append(row);}
  }
  $('.manage-categories').onclick=()=>{const box=$('.category-manager');box.hidden=!box.hidden;if(!box.hidden)manager();};
  function field(parent,label,value,key,multiline=false){const l=node('label',label,'field'),input=document.createElement(multiline?'textarea':'input');input.value=value||'';input.dataset.edit=key;if(multiline)input.rows=3;l.append(input);parent.append(l);return input;}
  async function detail(id){detailID=id;const item=await repo.getItem(id);if(detailID!==id)return;$('.library-list-view').hidden=true;$('.library-detail').hidden=false;const box=$('.library-detail');box.replaceChildren();const back=node('button','← 返回资料库','action');back.onclick=()=>{detailID=null;$('.library-detail').hidden=true;$('.library-list-view').hidden=false;list();};box.append(back,node('h2',item.expression),node('p',`${item.type} · ${item.reading} · 首次收录 ${date(item.createdAt)}\n已遇见 ${item.encounterCount} 次 · 已复习 ${item.reviewCount} 次\n下次复习 ${date(item.nextReviewAt)}`,'note'));
    const memberships=node('div','','detail-categories'),choose=node('button','选择分类 · 可多选','action');const showMemberships=()=>{const latest=repo.items.get(id)||item;memberships.textContent=repo.categoryIds(latest).map(cid=>repo.categoryList().find(c=>c.id===cid)?.name).join(' / ')||'未分类';};showMemberships();choose.onclick=()=>run(async()=>{await collection.open({itemId:id});showMemberships();});box.append(memberships,choose);
    field(box,'假名读音',item.reading,'reading');field(box,'英式 IPA',item.ipaUk,'ipaUk');field(box,'美式 IPA',item.ipaUs,'ipaUs');
    field(box,'中文释义',item.meaningZh,'meaningZh',true);field(box,'英文释义／检索词',item.meaningEn,'meaningEn');field(box,'标签（逗号分隔）',item.tags.join(', '),'tags');field(box,'备注',item.notes,'notes',true);field(box,'解释',item.explanation,'explanation',true);
    const typeLabel=node('label','资料类型（保留原始识别身份）','field'),typeSelect=document.createElement('select');typeSelect.dataset.edit='type';for(const type of ['vocabulary','grammar','loanword','english','custom']){const opt=node('option',type);opt.value=type;typeSelect.append(opt);}typeSelect.value=item.type;typeLabel.append(typeSelect);box.append(typeLabel);
    const state=node('label','学习状态','field'),select=document.createElement('select');select.dataset.edit='state';for(const [value,label]of Object.entries(STATE_LABELS)){const opt=node('option',label);opt.value=value;select.append(opt);}select.value=item.state;state.append(select);box.append(state);
    const save=node('button','保存修改','action primary');save.onclick=()=>run(async()=>{const changes=Object.fromEntries([...box.querySelectorAll('[data-edit]')].map(e=>[e.dataset.edit,e.dataset.edit==='tags'?[...new Set(e.value.split(/[,，]/).map(x=>x.trim()).filter(Boolean))]:e.value]));await repo.edit(id,changes);save.textContent='已保存';});box.append(save,node('h3','真实网页上下文'));
    let contextOffset=0;const contextsBox=node('div',''),more=node('button','加载更多上下文','action');box.append(contextsBox,more);
    const loadContexts=async()=>{const contexts=await repo.records('contexts',id,item.contextCount,contextOffset,10);for(const c of contexts){const section=node('div','','saved-context');section.append(node('small',c.previousSentence),node('p',c.sentence),node('small',c.nextSentence));const a=node('a',`${c.pageTitle} · ${c.domain}`);try{const url=new URL(c.url);if(['http:','https:'].includes(url.protocol)){a.href=url.href;a.target='_blank';a.rel='noopener noreferrer';}}catch{}section.append(a,node('small',date(c.encounteredAt)));contextsBox.append(section);}contextOffset+=contexts.length;more.hidden=contextOffset>=item.contextCount;};more.onclick=()=>run(loadContexts);await loadContexts();
  }
  async function nextQuiz(){const version=++runVersion;current=queue.shift();stats();if(!current){$('.quiz-view').hidden=true;put('.review-stats',$('.review-stats').textContent+'\n本轮已完成。短周期项目会在到期后重新出现。');return;}const contexts=await repo.records('contexts',current.id,current.contextCount,Math.max(0,current.contextCount-20),20);if(version!==runVersion||panel.hidden)return;quiz=makeQuiz(current,contexts,$('.quiz-mode').value);$('.quiz-view').hidden=false;put('.quiz-progress',`本轮还剩 ${queue.length+1} 项`);put('.quiz-prompt',quiz.prompt);put('.quiz-note',quiz.note||'根据真实掌握程度评分；不认识时请选「忘记」。');put('.quiz-origin',quiz.sentence?`来源：${quiz.contextSource}`:'暂无可用原句');put('.quiz-answer',quiz.answer);$('.quiz-answer').hidden=true;$('.quiz-pronunciation').hidden=true;$('.quiz-card').hidden=true;$('.grade-actions').hidden=true;$('.reveal').hidden=false;$('.quiz-choices').replaceChildren();for(const choice of quiz.choices||[]){const b=node('button',choice,'action');b.onclick=()=>{quiz.selected=choice;put('.quiz-note',choice===quiz.correct?'选择正确，请核对解释后评分。':'选择不符，请核对解释后评分。');reveal();};$('.quiz-choices').append(b);}}
  function reveal(){$('.quiz-answer').hidden=false;renderPronunciation($('.quiz-pronunciation'),{word:current.expression,base:current.normalizedExpression,reading:current.reading,lang:current.language|| (current.type==='english'?'en':'ja')},current);$('.quiz-card').hidden=false;$('.grade-actions').hidden=false;$('.reveal').hidden=true;const actions=$('.grade-actions');actions.replaceChildren();GRADES.forEach((grade,i)=>{const result=schedule(current,grade),b=node('button',`${['忘记','困难','一般','简单'][i]} · ${intervalLabel(result.currentInterval)}`,'action');b.onclick=()=>run(async()=>{for(const button of actions.children)button.disabled=true;try{await repo.review(current.id,grade,{mode:quiz.mode,prompt:quiz.prompt,selected:quiz.selected||'',correct:quiz.correct||'',contextSource:quiz.contextSource});await nextQuiz();}catch(e){for(const button of actions.children)button.disabled=false;throw e;}});actions.append(b);});}
  function changeTab(value){tab=value;$('.library-tab').classList.toggle('primary',value==='library');$('.review-tab').classList.toggle('primary',value==='review');$('.library-tab').setAttribute('aria-pressed',String(value==='library'));$('.review-tab').setAttribute('aria-pressed',String(value==='review'));detailID=null;runVersion++;$('.library-detail').hidden=true;$('.library-list-view').hidden=value!=='library';$('.review-view').hidden=value!=='review';$('.quiz-view').hidden=true;if(value==='library')list();else stats();}
  $('.close').onclick=()=>{panel.hidden=true;runVersion++;};$('.library-tab').onclick=()=>changeTab('library');$('.review-tab').onclick=()=>changeTab('review');$('.reveal').onclick=reveal;
  $('.library-search').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{offset=0;list();},160);};$('.library-filter').onchange=()=>{offset=0;list();};$('.previous').onclick=()=>{offset=Math.max(0,offset-40);list();};$('.next').onclick=()=>{offset+=40;list();};$('.repair').onclick=()=>run(async()=>{await repo.rebuildIndex();list();});
  for(const [value,label]of QUIZ_MODES){const o=node('option',label);o.value=value;$('.quiz-mode').append(o);}
  $('.quiz-card').onclick=()=>run(async()=>{if(current){await onRead(current.id);panel.hidden=true;}});
  $('.start-review').onclick=()=>run(async()=>{await repo.ready;queue=repo.due();await nextQuiz();});
  $('.custom-add').onclick=()=>{changeTab('library');detailID='custom';$('.library-list-view').hidden=true;$('.library-detail').hidden=false;const box=$('.library-detail');box.replaceChildren();field(box,'原文／表达','','word');field(box,'中文释义','','meaning',true);const save=node('button','收录自定义项目','action primary');save.onclick=()=>run(async()=>{const word=box.querySelector('[data-edit=word]').value.trim(),meaning=box.querySelector('[data-edit=meaning]').value.trim();if(!word||!meaning)throw new Error('请填写原文和释义。');const item=await collection.open({info:{word,base:word,type:'custom',lang:'custom'},entry:{meaning,source:'用户自定义'},context:null});if(item)await detail(item.id);});const cancel=node('button','返回','action');cancel.onclick=()=>changeTab('library');box.append(save,cancel);};
  repo.subscribe(()=>{list();if(tab==='review')stats();});
  return {position,async editItem(id){onOpen();panel.hidden=false;windowControl.raise();position();await run(()=>detail(id));},resume(){onOpen();panel.hidden=false;windowControl.raise();position();if(tab==='library')list();},isOpen:()=>!panel.hidden,close(){panel.hidden=true;runVersion++;},async open(value='library'){onOpen();panel.hidden=false;windowControl.raise();position();$('.close').focus();changeTab(value);put('.library-error','正在读取资料库…');await run(async()=>{await repo.ready;put('.library-error','');list();stats();});}};
}
